val maxSdkVers by extra(31)
val minSdkVers by extra(21)
val codeVers by extra(1)
val nameVers by extra("1.0")

val coroutinesVers by extra("1.5.2")
val lifecycleVers by extra("2.4.0")
val fragmentVers by extra("1.3.6")
val navigationVers by extra("2.3.5")
val hiltVers by extra("2.40.1")
val roomVers by extra("2.3.0")